// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdmnbujcoyxsazpuwgqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkbW5idWpjb3l4c2F6cHV3Z3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjA4OTUsImV4cCI6MjA2NTczNjg5NX0.QUBq2xY4P8hSDoVPKLAABHdGLlELQq34GTxCpxz5FLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);